recaptcha {
    // These keys are generated by the ReCaptcha service
	publicKey = "6LdKCd0SAAAAAJlTFqPn7Qv-9Aul_PmkAaPqsrQn"
	privateKey = "6LdKCd0SAAAAALUM0MybvMQVg3JgQ0Fz50EqSkRx"

	// Include the noscript tags in the generated captcha
	includeNoScript = true

    // Force language change. See this for more: http://code.google.com/p/recaptcha/issues/detail?id=133
    forceLanguageInURL = false
}

environments {
  development {
    recaptcha {
      // Set to false to disable the display of captcha
      enabled = false
      // Communicate using HTTPS
      useSecureAPI = false
    }
  }
  production {
    recaptcha {
      // Set to false to disable the display of captcha
      enabled = true
      // Communicate using HTTPS
      useSecureAPI = true
    }
  }
}